[package]
name = "ollama-rs-types"
edition = "2024"
version.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
schemars = { version = "0.8.22", features = ["preserve_order"] }